# Generated by Django 4.2.1 on 2023-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="band",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="bandmember",
            name="instrument",
        ),
        migrations.AddField(
            model_name="bandmember",
            name="location",
            field=models.ManyToManyField(to="mainsite.location"),
        ),
        migrations.AddField(
            model_name="band",
            name="genre",
            field=models.ManyToManyField(to="mainsite.genre"),
        ),
        migrations.AddField(
            model_name="bandmember",
            name="instrument",
            field=models.ManyToManyField(to="mainsite.instrument"),
        ),
    ]
