# Generated by Django 4.2.1 on 2023-08-28 11:59

from django.db import migrations

venues = [
    {
        "name": "The Earl Ferrers",
        "postcode": "SW16 1BT",
        "location": "Streatham",
    },
    {
        "name": "The Beehive",
        "postcode": "E3 3LT",
        "location": "Bow",
    },
    {
        "name": "Stags Head",
        "postcode": "N1 5RA",
        "location": "Hoxton",
    },
    {
        "name": "The Horn",
        "location": "St Albans",
        "postcode": "WD17 3RL",
    },
    {
        "name": "The Star in Shoreditch",
        "location": "Shoreditch",
        "postcode": "E1 6PU",
    },
    {
        "name": "Friars Inn",
        "location": "Hemel Hempstead",
        "postcode": "HP1 1BX",
    },
    {
        "name": "The Old Town Hall",
        "location": "Hemel Hempstead",
        "postcode": "HP1 3AE",
    },
    {
        "name": "Poco Loco",
        "location": "Chatham",
        "postcode": "ME4 4DS",
    },
    {
        "name": "The Fighting Cocks",
        "location": "Kingston",
        "postcode": "KT1 1QJ",
    },
    {
        "name": "The Engine Rooms",
        "location": "Bow",
        "postcode": "E3 3LT",
    },
    {
        "name": "The Rebel Inn",
        "postcode": "SW16 1BS",
        "location": "Streatham",
    },
    {
        "name": "The Horns",
        "postcode": "WD17 3RL",
        "location": "Watford",
    },
    {
        "name": "The Good Mixer",
        "postcode": "NW1 7HJ",
        "location": "Camden",
    },
    {
        "name": "The Macbeth",
        "postcode": "N1 6LP",
        "location": "Hoxton",
    },
    {
        "name": "The Amersham Arms",
        "postcode": "SE14 6TY",
        "location": "New Cross",
    },
    {
        "name": "New Cross Inn",
        "postcode": "SE14 6AS",
        "location": "New Cross",
    },
]


def create_venues(apps, schema_editor):
    Venue = apps.get_model("mainsite", "Venue")
    for venue in venues:
        Venue.objects.create(**venue)


class Migration(migrations.Migration):
    dependencies = [("mainsite", "0001_initial")]

    operations = [
        migrations.RunPython(create_venues),
    ]
