# Generated by Django 4.2.1 on 2023-07-23 17:13

from django.db import migrations, models


def create_defaults_instruments(apps, schema_editor):
    Instruments = apps.get_model("mainsite", "Instrument")
    Instruments.objects.create(name="Guitar")
    Instruments.objects.create(name="Bass")
    Instruments.objects.create(name="Drums")
    Instruments.objects.create(name="Vocals")
    Instruments.objects.create(name="Keyboard")
    Instruments.objects.create(name="Other")


def create_defaults_locations(apps, schema_editor):
    Location = apps.get_model("mainsite", "Location")
    Location.objects.create(name="London")
    Location.objects.create(name="Manchester")
    Location.objects.create(name="Leicester")
    Location.objects.create(name="Hemel")
    Location.objects.create(name="Other")


def create_defaults_genres(apps, schema_editor):
    Genre = apps.get_model("mainsite", "Genre")
    Genre.objects.create(name="Rock")
    Genre.objects.create(name="Pop")
    Genre.objects.create(name="Metal")
    Genre.objects.create(name="Punk")
    Genre.objects.create(name="Emo")
    Genre.objects.create(name="Country")
    Genre.objects.create(name="Other")


def delete_defaults(apps, schema_editor):
    Instrument = apps.get_model("mainsite", "Instrument")
    Location = apps.get_model("mainsite", "Location")
    Genre = apps.get_model("mainsite", "Genre")
    Instrument.objects.all().delete()
    Location.objects.all().delete()
    Genre.objects.all().delete()


def forward(apps, schema_editor):
    create_defaults_instruments(apps, schema_editor)
    create_defaults_locations(apps, schema_editor)
    create_defaults_genres(apps, schema_editor)


def reverse(apps, schema_editor):
    delete_defaults(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        (
            "mainsite",
            "0002_genre_instrument_location_remove_band_genre_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
