# Generated by Django 4.2.1 on 2023-08-28 11:59

from django.db import migrations


genres = [
    {"name": "Punk"},
    {"name": "Rock"},
    {"name": "Indie"},
    {"name": "Psych Rock"},
    {"name": "Pop"},
    {"name": "Emo"},
    {"name": "Funk"},
    {"name": "Electronic"},
]


def create_instruments(apps, schema_editor):
    Genre = apps.get_model("mainsite", "Genre")
    for genre in genres:
        Genre.objects.create(**genre)


class Migration(migrations.Migration):
    dependencies = [("mainsite", "0003_make_defaults_instruments")]

    operations = [
        migrations.RunPython(create_instruments),
    ]
