# Generated by Django 4.2.1 on 2023-08-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_remove_band_membership_remove_bandmember_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.band'),
        ),
    ]
