# Generated by Django 4.2.1 on 2023-08-28 11:27

from django.db import migrations, models
import django.db.models.deletion

venues = [
    {
        "name": "The Rebel Inn",
        "postcode": "SW16 1BS",
        "location": "Streatham",
    },
    {
        "name": "The Horns",
        "postcode": "WD17 3RL",
        "location": "Watford",
    },
    {
        "name": "The Good Mixer",
        "postcode": "NW1 7HJ",
        "location": "Camden",
    },
    {
        "name": "The Macbeth",
        "postcode": "N1 6LP",
        "location": "Hoxton",
    },
    {
        "name": "The Amersham Arms",
        "postcode": "SE14 6TY",
        "location": "New Cross",
    },
    {
        "name": "New Cross Inn",
        "postcode": "SE14 6AS",
        "location": "New Cross",
    },
]


def add_initial_venues(apps, schema_editor, venues):
    Venue = apps.get_model("mainsite", "Venue")
    for venue in venues:
        location = apps.get_model("mainsite", "Location").objects.get(
            name=venue["location"]
        )
        new_venue = Venue.objects.create(
            name=venue["name"], postcode=venue["postcode"], location=location
        )
        new_venue.save()


class Migration(migrations.Migration):
    dependencies = [
        ("mainsite", "0005_bandmember_band"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gig",
            name="location",
        ),
        migrations.AlterField(
            model_name="bandmember",
            name="band",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainsite.band"
            ),
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainsite.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gig",
            name="venue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainsite.venue",
            ),
        ),
    ]
