# Generated by Django 4.2.1 on 2023-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_remove_gig_location_alter_bandmember_band_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandmember',
            name='band',
        ),
        migrations.AddField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(blank=True, to='mainsite.bandmember'),
        ),
    ]
